### ISSUE TITLE
Error opening gazetteer index

### ISSUE THREAD

**Issue by rhazegh** [johnb30/cliff-docker#1]
`[cliff-docker (master)]$ curl http://localhost:8080/CLIFF-2.1.1/parse/text?q=test`

Gives the following error:

``` json
{
  "details":"com.bericotech.clavin.ClavinException: Error opening gazetteer index.", 
  "status":"error", 
  "milliseconds":6265, 
  "version":"2.1.1"
}
```

Any suggestion for fixing this issue?

The installation log from `docker build -t cliff:2.1.1 .` can be found here:
http://pastebin.com/K8SvwSnj

**Comment by rhazegh** [comment]
It looks like the instructions in `launch.sh` were not executed properly. 

I ran a `bash` shell to look around inside the container. Then ran the commands in `launch.sh` manually. It started building the index file but at some point it ran out of memory. How much memory is needed for finishing the indexing process?

```
23:02:41.484 [com.bericotech.clavin.index.IndexDirectoryBuilder.main()] INFO  - rowcount: 8900000
23:02:52.891 [com.bericotech.clavin.index.IndexDirectoryBuilder.main()] INFO  - rowcount: 9000000
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000007a611f000, 694501376, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 694501376 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /root/CLAVIN/hs_err_pid601.log
root@012b7022206e:~/CLAVIN# free -mt
             total       used       free     shared    buffers     cached
Mem:          3764       1415       2348        139          2        626
-/+ buffers/cache:        786       2977
Swap:            0          0          0
Total:        3764       1415       2348
```

**Comment by johnb30** [comment]
Thanks for looking at the output of the `launch.sh` script. The CLAVIN index is really hungry. I usually run on servers with 8gb, but I think 4gb should probably be sufficient. I'll add a note to the README about RAM usage.
